// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package tinyorm

import (
	"tinyorm/dialect"
	"tinyorm/internal/db"
	"tinyorm/options"
	"tinyorm/session"
)

// Injectors from wire.go:

func NewTinyOrm(Opts options.Options) (*Engine, error) {
	sqlDB, err := db.ProviderDB(Opts)
	if err != nil {
		return nil, err
	}
	dialectDialect, err := dialect.ProviderDialect(Opts)
	if err != nil {
		return nil, err
	}
	sessionSession, err := session.NewSession(sqlDB, dialectDialect)
	if err != nil {
		return nil, err
	}
	tinyOrm := &Engine{
		Opts:    Opts,
		db:      sqlDB,
		dialect: dialectDialect,
		session: sessionSession,
	}
	return tinyOrm, nil
}
